# DankSearch Configuration
# See https://github.com/AvengeMedia/danksearch for documentation

index_path = "/home/zazag/.cache/danksearch/index"
listen_addr = ":43654"
max_file_bytes = 2097152
worker_count = 6
text_extensions = [".txt", ".md", ".go", ".py", ".js", ".ts", ".jsx", ".tsx", ".json", ".yaml", ".yml", ".toml", ".html", ".css", ".rs", ".c", ".cpp", ".h", ".java", ".rb", ".php", ".sh"]
index_all_files = true
max_depth = 0

[[index_paths]]
  path = "/home/zazag/Documents/"
  max_depth = 6
  exclude_hidden = true
  exclude_dirs = []
  extract_exif = true

[[index_paths]]
  path = "/home/zazag/Pictures/"
  max_depth = 6
  exclude_hidden = true
  exclude_dirs = ["Share"]
  extract_exif = true

[[index_paths]]
  path = "/home/zazag/Videos/"
  max_depth = 6
  exclude_hidden = true
  exclude_dirs = []
  extract_exif = true

[[index_paths]]
  path = "/home/zazag/Music/"
  max_depth = 6
  exclude_hidden = true
  exclude_dirs = []
  extract_exif = true

[[index_paths]]
  path = "/home/zazag/Downloads/"
  max_depth = 6
  exclude_hidden = true
  exclude_dirs = []
  extract_exif = true
